WITH CTE AS(
select top 10000   [SAV]
--, patindex('%]%',[SAV])  
, SUBSTRING([SAV],1,  patindex('%]%',[SAV] ))  AS CREATED 
--, REVERSE([SAV])
--, patindex('%, ]%',REVERSE([SAV])) 
, REVERSE( SUBSTRING( REVERSE([SAV]), 1, patindex('%, ]%',REVERSE([SAV]) ))) AS MODIFIED
 from [mig].[MIGRN_ALL]
) 
,
CTE2 AS(
SELECT [SAV]
, CREATED
,LEFT(CREATED,CHARINDEX('|',CREATED)) AS CREATEDBY
,SUBSTRING(CREATED,CHARINDEX('|',CREATED),100) AS CREATEDON
,  MODIFIED
, LEFT(MODIFIED,CHARINDEX('|',MODIFIED)) AS MODIFIEDBY
,SUBSTRING(MODIFIED,CHARINDEX('|',MODIFIED),100) AS MODIFIEDON
FROM CTE
)
SELECT 
[SAV]
,REPLACE(REPLACE(CREATEDBY,'[',''),'|','')
,TRY_CONVERT(DATETIME, REPLACE(REPLACE(CREATEDON ,']',''),'|',''),103)
, SUBSTRING(REPLACE(REPLACE(MODIFIEDBY,'[',''),'|',''),charindex(',',MODIFIEDBY)+1,100)
,TRY_CONVERT(DATETIME, REPLACE(REPLACE(MODIFIEDON,']',''),'|',''),103)
 FROM CTE2
 
;

--=======================
--[dbo].[PatientEntities]
--=======================
 WITH CTE AS(
select   URNO,
 [CreatedBy] AS SAV
--, patindex('%]%',[SAV])  
, SUBSTRING([CreatedBy],1,  patindex('%]%',[CreatedBy] ))  AS CREATED 
--, REVERSE([SAV])
--, patindex('%, ]%',REVERSE([SAV])) 
, REVERSE( SUBSTRING( REVERSE([CreatedBy]), 1, patindex('%, ]%',REVERSE([CreatedBy]) ))) AS MODIFIED
 from [dbo].[PatientEntities]
) 
,
CTE2 AS(
SELECT [SAV],URNo
, CREATED
,LEFT(CREATED,CHARINDEX('|',CREATED)) AS CREATEDBY
,SUBSTRING(CREATED,CHARINDEX('|',CREATED),100) AS CREATEDON
,  MODIFIED
, LEFT(MODIFIED,CHARINDEX('|',MODIFIED)) AS MODIFIEDBY
,SUBSTRING(MODIFIED,CHARINDEX('|',MODIFIED),100) AS MODIFIEDON
FROM CTE
),
CTE3 AS(
SELECT 
[SAV],URNO
,REPLACE(REPLACE(CREATEDBY,'[',''),'|','') AS CREATEDBY
,REPLACE(REPLACE(CREATEDON ,']',''),'|','') AS CREATEDON
, SUBSTRING(REPLACE(REPLACE(MODIFIEDBY,'[',''),'|',''),charindex(',',MODIFIEDBY)+1,100)  AS MODIFIEDBY
,REPLACE(REPLACE(MODIFIEDON,']',''),'|','')  AS MODIFIEDON
 FROM CTE2
 )
 UPDATE [dbo].[PatientEntities] SET
 CreatedBy=CTE3.CREATEDBY,
 CreatedOn= TRY_CONVERT(DATETIME,SUBSTRING(CTE3.CREATEDON,1,17),103),
 ModifiedBy=CTE3.MODIFIEDBY,
 ModifiedOn= TRY_CONVERT(DATETIME,SUBSTRING(CTE3.MODIFIEDON,1,17),103)
 from CTE3 
 INNER JOIN  [dbo].[PatientEntities] As P ON CTE3.URNo=P.URNo

 
--=======================
--[dbo].[Triages]
--=======================
 WITH CTE AS(
select   BHURNO AS URNO,
 [CreatedBy] AS SAV
--, patindex('%]%',[SAV])  
, SUBSTRING([CreatedBy],1,  patindex('%]%',[CreatedBy] ))  AS CREATED 
--, REVERSE([SAV])
--, patindex('%, ]%',REVERSE([SAV])) 
, REVERSE( SUBSTRING( REVERSE([CreatedBy]), 1, patindex('%, ]%',REVERSE([CreatedBy]) ))) AS MODIFIED
 from [dbo].[Triages]
) 
,
CTE2 AS(
SELECT [SAV],URNo
, CREATED
,LEFT(CREATED,CHARINDEX('|',CREATED)) AS CREATEDBY
,SUBSTRING(CREATED,CHARINDEX('|',CREATED),100) AS CREATEDON
,  MODIFIED
, LEFT(MODIFIED,CHARINDEX('|',MODIFIED)) AS MODIFIEDBY
,SUBSTRING(MODIFIED,CHARINDEX('|',MODIFIED),100) AS MODIFIEDON
FROM CTE
),
CTE3 AS(
SELECT 
[SAV],URNO
,REPLACE(REPLACE(CREATEDBY,'[',''),'|','') AS CREATEDBY
,REPLACE(REPLACE(CREATEDON ,']',''),'|','') AS CREATEDON
, SUBSTRING(REPLACE(REPLACE(MODIFIEDBY,'[',''),'|',''),charindex(',',MODIFIEDBY)+1,100)  AS MODIFIEDBY
,REPLACE(REPLACE(MODIFIEDON,']',''),'|','')  AS MODIFIEDON
 FROM CTE2
 )
 UPDATE [dbo].[Triages] SET
 CreatedBy=CTE3.CREATEDBY,
 CreatedOn= TRY_CONVERT(DATETIME,SUBSTRING(CTE3.CREATEDON,1,17),103),
 ModifiedBy=CTE3.MODIFIEDBY,
 ModifiedOn= TRY_CONVERT(DATETIME,SUBSTRING(CTE3.MODIFIEDON,1,17),103)
 from CTE3 
 INNER JOIN  [dbo].[Triages] As P ON CTE3.URNo=P.BhUrNo
