--CREATE SCHEMA [mig]

CREATE TABLE [mig].[migrn_risk_grid_pivot] 
(
	Id int PRIMARY KEY NOT NULL IDENTITY(1,1),
	[RecNo] varchar(10),
	[Suicidality] varchar(10),
	[Deliberate Self Harm] varchar(10),
	[Aggression] varchar(10),
	[Risk to Others] varchar(10),
	[Avoiding Contact] varchar(10),
	[Substance Abuse] varchar(10),
	[Inapprop.Sexual Behaviour] varchar(10),
	[Cognitive Impairment] varchar(10),
	[Serious Medical Condition] varchar(10),
	[Level of Non-compliance] varchar(10),
	[Cultural Risk] varchar(10),
	[Vulnerability to Exploitation] varchar(10),
	[Falls] varchar(10),
	[Other (specify)] varchar(10),
	[Referrers Risk Assessment] varchar(10),
	[OVERALL RISK RATING] varchar(10)
)

GO
CREATE TABLE [mig].[migrn_risk_grid_pivot_comments] 
(
	Id int PRIMARY KEY NOT NULL IDENTITY(1,1),
	[RecNo ] varchar(10),
	[Suicidality Rx] varchar(500),
	[Deliberate Self Harm Rx] varchar(500),
	[Aggression Rx] varchar(500),
	[Risk to Others Rx] varchar(500),
	[Avoiding Contact Rx] varchar(500),
	[Substance Abuse Rx] varchar(500),
	[Inapprop.Sexual Behaviour Rx] varchar(500),
	[Cognitive Impairment Rx] varchar(500),
	[Serious Medical Condition Rx] varchar(500),
	[Level of Non-compliance Rx] varchar(500),
	[Cultural Risk Rx] varchar(500),
	[Vulnerability to Exploitation Rx] varchar(500),
	[Falls Rx] varchar(500),
	[Other (specify) Rx] varchar(500),
	[Referrers Risk Assessment Rx] varchar(500),
	[OVERALL RISK RATING Rx] varchar(500)
)
GO
CREATE TABLE [mig].[migrn_risk_non_grid_pivot] 
(
	Id int PRIMARY KEY NOT NULL IDENTITY(1,1),	
[RecNo] varchar(10)	,
[COM]	varchar(max),
[FOR]	varchar(max),
[EPY]	varchar(10)	,
[EPN]	varchar(10)	,
[EPP]	varchar(10)	,
[HIN]	varchar(10)	,
[HIY]	varchar(10)	
)
GO
--DROP TABLE [mig].[migrn_all]
CREATE TABLE [mig].[migrn_all](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[recnumber] [int] NULL,
	[delflag] [bit] NULL,
	[reftype] [varchar](50) NULL,
	[recfin] [bit] NULL,
	[recfindate] [varchar](20) NULL,
	[unregloc] [int] NULL,
	[locrec] [int] NULL,
	[URNO] [int] NULL,
	[lname] [varchar](200) NULL,
	[FNAME] [varchar](200) NULL,
	[dob]  [varchar](20) NULL,
	[Male] [bit] NULL,
	[Female] [bit] NULL,
	[marital] [varchar](50) NULL,
	[Address] [varchar](500) NULL,
	[town] [varchar](50) NULL,
	[state] [varchar](50) NULL,
	[patphone] [varchar](100) NULL,
	[gp] [varchar](200) NULL,
	[gpphone] [varchar](100) NULL,
	[abo] [bit] NULL,
	[tsi] [bit] NULL,
	[cob] [varchar](50) NULL,
	[nation] [varchar](50) NULL,
	[flang] [varchar](50) NULL,
	[interpyes] [bit] NULL,
	[interpno] [bit] NULL,
	[parent] [varchar](50) NULL,
	[nok] [varchar](50) NULL,
	[nokrelat] [varchar](50) NULL,
	[nokaddr] [varchar](500) NULL,
	[noktown] [varchar](50) NULL,
	[nokstate] [varchar](50) NULL,
	[nokphone] [varchar](50) NULL,
	[gpawareyes] [bit] NULL,
	[gpawareno] [bit] NULL,
	[clientawareyes] [bit] NULL,
	[clientawareno] [bit] NULL,
	[refdate]  [varchar](20) NULL,
	[reftime]  [varchar](20)NULL,
	[refname] [varchar](50) NULL,
	[reforigin] [varchar](50) NULL,
	[refrelat] [varchar](50) NULL,
	[refcontact] [varchar](50) NULL,
	[refmedium] [varchar](50) NULL,
	[amhsreg] [varchar](50) NULL,
	[respcat] [varchar](1) NULL,
	[resptxt] [varchar](50) NULL,
	[pastcon] [varchar](50) NULL,
	[rapnosearch] [bit] NULL,
	[rapnotfound] [bit] NULL,
	[rapfound] [bit] NULL,
	[rapdx] [varchar](500) NULL,
	[accserv] [bit] NULL,
	[notaccserv] [bit] NULL,
	[serv] [varchar](500) NULL,
	[oth] [varchar](500) NULL,
	[faxyes] [bit] NULL,
	[faxno] [bit] NULL,
	[faxdate]  [varchar](20) NULL,
	[discussyes] [bit] NULL,
	[discussno] [bit] NULL,
	[discusstime]  [varchar](20) NULL,
	[triclin] [varchar](500) NULL,
	[contdur] [varchar](200) NULL,
	[signoff] [varchar](200) NULL,
	[signoffdate]  [varchar](20) NULL,
	[prog] [varchar](200) NULL,
	[medium] [varchar](100) NULL,
	[locat] [varchar](200) NULL,
	[servrecpt] [varchar](200) NULL,
	[servresp] [varchar](200) NULL,
	[servdate] [varchar](20) NULL,
	[servtime] [varchar](20) NULL,
	[KID] [varchar](500) NULL,
	[PRO] [varchar](max) NULL,
	[MED] [varchar](max) NULL,
	[REQ] [varchar](max) NULL,
	[CMI] [varchar](max) NULL,
	[ALT] [varchar](max) NULL,
	[CRI] [varchar](max) NULL,
	[WAR] [varchar](max) NULL,
	[AGY] [varchar](max) NULL,
	[CON] [varchar](max) NULL,
	[INV] [varchar](max) NULL,
	[PAS] [varchar](max) NULL,
	[TRI] [varchar](max) NULL,
	[DET] [varchar](max) NULL,
	[OUT] [varchar](max) NULL,
	[CNO] [varchar](max) NULL,
	[SAV] [varchar](max) NULL,
	[COM] [varchar](max) NULL,
	[FOR] [varchar](max) NULL,
	[EPY] [bit] NULL,
	[EPN] [bit] NULL,
	[EPP] [bit] NULL,
	[HIN] [bit] NULL,
	[HIY] [bit] NULL,
	[Suicidality] [varchar](10) NULL,
	[Deliberate Self Harm] [varchar](10) NULL,
	[Aggression] [varchar](10) NULL,
	[Risk to Others] [varchar](10) NULL,
	[Avoiding Contact] [varchar](10) NULL,
	[Substance Abuse] [varchar](10) NULL,
	[Inapprop.Sexual Behaviour] [varchar](10) NULL,
	[Cognitive Impairment] [varchar](10) NULL,
	[Serious Medical Condition] [varchar](10) NULL,
	[Level of Non-compliance] [varchar](10) NULL,
	[Cultural Risk] [varchar](10) NULL,
	[Vulnerability to Exploitation] [varchar](10) NULL,
	[Falls] [varchar](10) NULL,
	[Other (specify)] [varchar](10) NULL,
	[Referrers Risk Assessment] [varchar](10) NULL,
	[OVERALL RISK RATING] [varchar](10) NULL,
	[Suicidality Rx] [varchar](500) NULL,
	[Deliberate Self Harm Rx] [varchar](500) NULL,
	[Aggression Rx] [varchar](500) NULL,
	[Risk to Others Rx] [varchar](500) NULL,
	[Avoiding Contact Rx] [varchar](500) NULL,
	[Substance Abuse Rx] [varchar](500) NULL,
	[Inapprop.Sexual Behaviour Rx] [varchar](500) NULL,
	[Cognitive Impairment Rx] [varchar](500) NULL,
	[Serious Medical Condition Rx] [varchar](500) NULL,
	[Level of Non-compliance Rx] [varchar](500) NULL,
	[Cultural Risk Rx] [varchar](500) NULL,
	[Vulnerability to Exploitation Rx] [varchar](500) NULL,
	[Falls Rx] [varchar](500) NULL,
	[Other (specify) Rx] [varchar](500) NULL,
	[Referrers Risk Assessment Rx] [varchar](500) NULL,
	[OVERALL RISK RATING Rx] [varchar](500) NULL
)